#!/usr/bin/dash
for N in $(/usr/bin/kubectl get nodepools -o name) ; do /usr/bin/kubectl patch ${N} --type merge --patch '{"spec": {"limits": {"cpu": 0}}}' ; done
/usr/bin/kubectl drain --ignore-daemonsets=true --delete-emptydir-data=true --disable-eviction=true -l karpenter.sh/registered=true && /usr/bin/kubectl delete node -l karpenter.sh/registered=true
