#!/usr/bin/dash
for N in $(/usr/bin/kubectl get nodepools -o name) ; do /usr/bin/kubectl patch ${N} --type merge --patch '{"spec": {"limits": {"cpu": 0}}}' ; done
/usr/bin/kubectl delete nodeclaims --all
